---
- name: install python-apt on ansible < 1.6.0 and ubuntu et al
  sudo: yes
  raw: >
    if > /dev/null command -v apt-get; then
       python -c "import apt" ||
       (> /dev/null command -v apt-get && apt-get install -y python-apt);
    fi
  changed_when: False

- name: apt-get update
  apt: update_cache=true cache_valid_time=3600
  sudo: yes

- name: Install rawtherapee
  apt: name=rawtherapee
  sudo: yes
